import type { EnemyDef } from '@/game/engine/types';

/**
 * Враги — таблицы 7.1 и 7.2 ТЗ (+ босс «Горгак» карты 1 из таблицы 6.4 / TC-08).
 */
export const ENEMIES: Record<string, EnemyDef> = {
  goblin: {
    id: 'goblin',
    name: { ru: 'Гоблин', en: 'Goblin' },
    role: { ru: 'Масса', en: 'Mass' },
    category: 'normal',
    hp: 45, speed: 1.6, reward: 4, meleeDamage: 4,
    armor: 0, magicResist: 0,
    leakLives: 1, flying: false, bossTier: 0, blockable: true,
    spriteSize: 44,
    abilities: [],
    desc: {
      ru: 'Мелкий и быстрый. Опасен только в плотной толпе — ответ: пушка или площадный урон.',
      en: 'Small and fast. Dangerous only in dense crowds — answer with cannon or AoE damage.',
    },
  },
  wolf: {
    id: 'wolf',
    name: { ru: 'Волк', en: 'Wolf' },
    role: { ru: 'Бегун', en: 'Runner' },
    category: 'normal',
    hp: 70, speed: 2.6, reward: 6, meleeDamage: 5,
    armor: 0, magicResist: 0,
    leakLives: 1, flying: false, bossTier: 0, blockable: true,
    spriteSize: 50,
    abilities: [],
    desc: {
      ru: 'Очень быстрый. Замедляйте магической башней (2 ур. «Иней») или перехватывайте казармами на прямом участке.',
      en: 'Very fast. Slow it with a magic tower (L2 Rime) or intercept with barracks on a straight run.',
    },
  },
  orc: {
    id: 'orc',
    name: { ru: 'Орк', en: 'Orc' },
    role: { ru: 'Базовая пехота', en: 'Basic infantry' },
    category: 'normal',
    hp: 150, speed: 1.1, reward: 10, meleeDamage: 8,
    armor: 0, magicResist: 0,
    leakLives: 1, flying: false, bossTier: 0, blockable: true,
    spriteSize: 52,
    abilities: [],
    desc: {
      ru: 'Крепкий боец среднего темпа. Универсальные башни справляются, казармы удерживают.',
      en: 'Sturdy mid-tempo fighter. Universal towers handle it; barracks hold it in place.',
    },
  },
  bandit: {
    id: 'bandit',
    name: { ru: 'Бандит', en: 'Bandit' },
    role: { ru: 'Хитрец', en: 'Trickster' },
    category: 'normal',
    hp: 110, speed: 1.5, reward: 9, meleeDamage: 7,
    armor: 0.1, magicResist: 0,
    leakLives: 1, flying: false, bossTier: 0, blockable: true,
    spriteSize: 48,
    abilities: [{ type: 'dodge', chance: 0.1 }],
    desc: {
      ru: 'Уворачивается от 10% физических попаданий. Магический урон надёжен против него.',
      en: 'Dodges 10% of physical hits. Magical damage is reliable against him.',
    },
  },
  harpy: {
    id: 'harpy',
    name: { ru: 'Гарпия', en: 'Harpy' },
    role: { ru: 'Летун', en: 'Flyer' },
    category: 'normal',
    hp: 90, speed: 1.9, reward: 8, meleeDamage: 0,
    armor: 0, magicResist: 0,
    leakLives: 1, flying: true, bossTier: 0, blockable: false,
    spriteSize: 50,
    abilities: [],
    desc: {
      ru: 'Летит по прямой к выходу, не блокируется солдатами. Пушка и казармы бесполезны.',
      en: 'Flies straight to the exit; soldiers cannot block it. Cannon and barracks are useless.',
    },
  },
  shaman: {
    id: 'shaman',
    name: { ru: 'Шаман', en: 'Shaman' },
    role: { ru: 'Поддержка', en: 'Support' },
    category: 'normal',
    hp: 130, speed: 1.2, reward: 14, meleeDamage: 5,
    armor: 0, magicResist: 0.3,
    leakLives: 1, flying: false, bossTier: 0, blockable: true,
    spriteSize: 50,
    abilities: [
      { type: 'heal', hps: 18, targets: 2, radius: 2.0, priority: 'elite', keepDistance: 3.0 },
    ],
    desc: {
      ru: 'Лечит 18 HP/с двум союзникам в радиусе 2 клеток, приоритет — элите. Держится позади строя. Ставьте приоритет Strong.',
      en: 'Heals 18 HP/s to two allies within 2 cells, prioritizing elites. Stays behind the line. Use Strong priority.',
    },
  },
  necromancer: {
    id: 'necromancer',
    name: { ru: 'Некромант', en: 'Necromancer' },
    role: { ru: 'Призыв', en: 'Summoner' },
    category: 'normal',
    hp: 240, speed: 1.0, reward: 16, meleeDamage: 6,
    armor: 0, magicResist: 0.4,
    leakLives: 1, flying: false, bossTier: 0, blockable: true,
    spriteSize: 54,
    abilities: [{ type: 'summon', interval: 8, count: 2, summonType: 'skeleton' }],
    desc: {
      ru: 'Каждые 8 секунд призывает двух скелетов. Скелеты не дают золота и не считаются в завершении волны.',
      en: 'Summons two skeletons every 8 seconds. Skeletons give no gold and do not count towards wave completion.',
    },
  },
  skeleton: {
    id: 'skeleton',
    name: { ru: 'Скелет', en: 'Skeleton' },
    role: { ru: 'Призванный', en: 'Summoned' },
    category: 'normal',
    hp: 25, speed: 1.8, reward: 0, meleeDamage: 3,
    armor: 0, magicResist: 0,
    leakLives: 1, flying: false, bossTier: 0, blockable: true,
    spriteSize: 42,
    abilities: [],
    desc: {
      ru: 'Призван некромантом. Не даёт ни золота, ни опыта; в завершении волны не учитывается.',
      en: 'Summoned by necromancers. Gives neither gold nor XP; ignored for wave completion.',
    },
  },
  troll: {
    id: 'troll',
    name: { ru: 'Тролль', en: 'Troll' },
    role: { ru: 'Регенератор', en: 'Regenerator' },
    category: 'elite',
    hp: 480, speed: 0.9, reward: 30, meleeDamage: 14,
    armor: 0.2, magicResist: 0,
    leakLives: 2, flying: false, bossTier: 0, blockable: true,
    spriteSize: 62,
    blockMaxSeconds: 5,
    abilities: [{ type: 'regen', regenHps: 8 }],
    desc: {
      ru: 'Регенерирует 8 HP/с вне блока. Яд лучников (3 ур.) останавливает регенерацию и выжимает урон из долгого контакта.',
      en: 'Regenerates 8 HP/s while unblocked. Archer poison (L3) halts regeneration and exploits long contact.',
    },
  },
  demon: {
    id: 'demon',
    name: { ru: 'Демон', en: 'Demon' },
    role: { ru: 'Антимагия', en: 'Anti-magic' },
    category: 'elite',
    hp: 340, speed: 1.4, reward: 24, meleeDamage: 12,
    armor: 0, magicResist: 0.6,
    leakLives: 2, flying: false, bossTier: 0, blockable: true,
    spriteSize: 58,
    blockMaxSeconds: 5,
    abilities: [{ type: 'explode', damage: 15, explodeRadius: 1.0 }],
    desc: {
      ru: 'Сопротивление магии 60%. При смерти взрывается: 15 урона солдатам в 1 клетке. Бейте физическим.',
      en: '60% magic resistance. Explodes on death: 15 damage to soldiers within 1 cell. Use physical damage.',
    },
  },
  golem: {
    id: 'golem',
    name: { ru: 'Голем', en: 'Golem' },
    role: { ru: 'Танк', en: 'Tank' },
    category: 'elite',
    hp: 850, speed: 0.7, reward: 40, meleeDamage: 20,
    armor: 0.4, magicResist: -0.2,
    leakLives: 2, flying: false, bossTier: 0, blockable: true,
    spriteSize: 64,
    abilities: [{ type: 'stompHit', stun: 1.5 }],
    desc: {
      ru: 'Броня 40%, но уязвим к магии (−20%). Каждый удар оглушает блокирующего солдата на 1.5 с.',
      en: '40% armor but vulnerable to magic (−20%). Each hit stuns the blocking soldier for 1.5 s.',
    },
  },
  goblin_king: {
    id: 'goblin_king',
    name: { ru: 'Гоблин-король', en: 'Goblin King' },
    role: { ru: 'Мини-босс', en: 'Mini-boss' },
    category: 'miniboss',
    hp: 900, speed: 1.0, reward: 80, meleeDamage: 15,
    armor: 0.2, magicResist: 0.2,
    leakLives: 5, flying: false, bossTier: 1, blockable: true,
    spriteSize: 72,
    blockMaxSeconds: 5,
    abilities: [{ type: 'rage', threshold: 0.5, speedBonus: 0.3 }],
    desc: {
      ru: 'Чекпоинт DPS на 10-й волне. Ниже 50% HP ускоряется на 30%. Блокируется лишь на 5 секунд.',
      en: 'A DPS checkpoint on wave 10. Below 50% HP gains 30% speed. Can be blocked for only 5 seconds.',
    },
  },
  gorgak: {
    id: 'gorgak',
    name: { ru: 'Горгак, вождь гоблинов', en: 'Gorgak, Goblin Warlord' },
    role: { ru: 'Босс', en: 'Boss' },
    category: 'boss',
    hp: 1400, speed: 0.9, reward: 180, meleeDamage: 18,
    armor: 0.3, magicResist: 0.2,
    leakLives: 10, flying: false, bossTier: 1, blockable: true,
    spriteSize: 84,
    blockMaxSeconds: 5,
    abilities: [{ type: 'rage', threshold: 0.5, speedBonus: 0.3 }],
    desc: {
      ru: 'Босс финальной волны. Эскорт отвлекает огонь — решайте, кого бить первыми. Утечка стоит 10 жизней.',
      en: 'Final-wave boss. The escort distracts your fire — choose targets wisely. A leak costs 10 lives.',
    },
  },
  golem_patriarch: {
    id: 'golem_patriarch',
    name: { ru: 'Голем-праотец', en: 'Golem Patriarch' },
    role: { ru: 'Босс', en: 'Boss' },
    category: 'boss',
    hp: 3200, speed: 0.65, reward: 220, meleeDamage: 30,
    armor: 0.5, magicResist: -0.2,
    leakLives: 10, flying: false, bossTier: 1, blockable: false,
    spriteSize: 96,
    abilities: [{ type: 'stompAoE', interval: 4, stun: 1.5, radius: 1.0 }],
    desc: {
      ru: 'Не подлежит блоку. Каждые 4 секунды — топот: стан 1.5 с всем солдатам в 1 клетке. Магия бьёт его больнее (−20%).',
      en: 'Cannot be blocked. Every 4 seconds — a stomp: 1.5 s stun to all soldiers within 1 cell. Magic hits it harder (−20%).',
    },
  },
  dragon: {
    id: 'dragon',
    name: { ru: 'Дракон', en: 'Dragon' },
    role: { ru: 'Финальный босс', en: 'Final boss' },
    category: 'boss',
    hp: 6000, speed: 0.8, reward: 500, meleeDamage: 40,
    armor: 0.3, magicResist: 0.5,
    leakLives: 10, flying: true, bossTier: 2, blockable: false,
    spriteSize: 110,
    abilities: [
      { type: 'breath', dps: 60, breathRadius: 2.5, breathDuration: 3 },
      { type: 'summonFlying', interval: 20, count: 2, summonType: 'harpy' },
    ],
    desc: {
      ru: 'Летит по прямой, не блокируется. Огненное дыхание 60 DPS выжигает солдат, каждые 20 с призывает гарпий. Итог всей кампании.',
      en: 'Flies straight, cannot be blocked. Fiery breath (60 DPS) burns soldiers; summons harpies every 20 s. The campaign finale.',
    },
  },
};

export const ENEMY_ORDER = [
  'goblin', 'wolf', 'orc', 'bandit', 'harpy', 'shaman', 'necromancer', 'skeleton',
  'troll', 'demon', 'golem', 'goblin_king', 'gorgak', 'golem_patriarch', 'dragon',
];
